# Generated by Django 4.2.2 on 2023-06-24 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='App1Etiqueta',
        ),
        migrations.DeleteModel(
            name='App1Tarea',
        ),
    ]
