# Generated by Django 4.2.2 on 2023-06-24 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(choices=[('Trabajo', 'Trabajo'), ('Hogar', 'Hogar'), ('Estudio', 'Estudio'), ('Deporte', 'Deporte'), ('Personal', 'Personal'), ('Entretención', 'Entretención'), ('Otro', 'Otro')], default='Otro', max_length=20)),
                ('borrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=20)),
                ('borrado', models.BooleanField(default=False)),
                ('etiqueta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarea', to='app_1.etiqueta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
