# Generated by Django 4.2.2 on 2023-06-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Progreso', 'En progreso'), ('Completada', 'Completada')], default='Pendiente', max_length=20),
        ),
    ]
