# Generated by Django 4.2.2 on 2023-06-25 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_alter_tarea_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea',
            name='borrado',
        ),
    ]
