# Generated by Django 4.2.2 on 2023-07-05 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0004_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prioridad',
            options={},
        ),
        migrations.AddField(
            model_name='tarea',
            name='prioridad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app_1.prioridad'),
        ),
    ]
